// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYFweej2NFGW2ifJfSpvvA0SbZdq3Tl3E',
    appId: '1:128088765033:android:972f2d6b8782657202e8f8',
    messagingSenderId: '128088765033',
    projectId: 'laundryfirebasebackend',
    databaseURL: 'https://laundryfirebasebackend-default-rtdb.firebaseio.com',
    storageBucket: 'laundryfirebasebackend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtfb5rtrCFsj9uPnHQJZOP7wLc91v_u8I',
    appId: '1:128088765033:ios:b3e1d7bf4e4f514002e8f8',
    messagingSenderId: '128088765033',
    projectId: 'laundryfirebasebackend',
    databaseURL: 'https://laundryfirebasebackend-default-rtdb.firebaseio.com',
    storageBucket: 'laundryfirebasebackend.appspot.com',
    iosClientId: '128088765033-c59t2d12sf5b0fv0r4let3l39m1euk6k.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.login',
  );
}
